# WAF buildscript
# :vim set ft=python

def options(opt):
    opt.load("compiler_c")
    opt.load("compiler_cxx")
    opt.load("c")
    opt.load("cxx")
    #opt.load("qt5")


def configure(cnf):
    cnf.load("compiler_c")
    cnf.load("compiler_cxx")
    cnf.load("c")
    cnf.load("cxx")
    #cnf.load("qt5")


def build(bld):
    bld.program(
        features="c cprogram",
        source="main.c",
        target="testdy",

        includes=[".."],
        #defines=["__LIBDY_LIBRARY"],
        cflags=["-std=c11"],
        use="dy"
    )
    
    bld.program(
        features="cxx cxxprogram",
        source="main.cpp",
        target="testdypp",
        
        includes=[".."],
        cxxflags=["-std=c++14"],
        use="dy++",
    )

    bld.program(
        features="c cprogram",
        source="test_json.c",
        target="test_json",

        includes=[".."],
        cflags=["-std=c11"],
        use="dy",
    )

    bld.program(
        features="c cprogram",
        source="test_jsonfile.c",
        target="test_jsonfile",

        includes=[".."],
        cflags=["-std=c11"],
        use="dy",
    )

    # TODO: figure out Qt build
    #bld.program(
    #    features="qt5 cxx cxxprogram",
    #    source="test_qt.cpp",
    #    target="test_qt",
    #    includes=["..", "/usr/include/qt"],
    #    cxxflags=["-std=c++14"],
    #    uselib="QTCORE",
    #    use="dy++",
    #)
