# WAF buildscript
# :vim set ft=python

headers = ()
public_headers = "dy++.h", "dy++impl.h", "dy++conv.h", "callable.h"
sources = "dy++.cpp",

def options(opt):
    opt.load("compiler_cxx")


def configure(cnf):
    cnf.load("compiler_cxx")

    cnf.write_config_header("config.h")


def build(bld):
    bld.shlib(
    	source=sources,
    	target="dy++",

    	includes=[".", ".."],
    	defines=["__LIBDYPP_LIBRARY"],
    	cxxflags=["-std=c++14"],
    	use="dy"
    )
